### ISSUE TITLE
Update test suite

### ISSUE THREAD

**Issue by vrothberg** [kubic-project/velum#192]
Random tests break on random builds for random versions of Ruby. That's pretty bad as a reliable CI is our backbone.

Let's use this issue to track progress on this topic.

**Comment by vitoravelino** [comment]
I've been seeing two problems so far that it's becoming annoying for feature specs:

- not being able to reach an address, complains to dns or something like that
- false negatives (always when js: true)

For the first one, I guess we can't do anything since it's inside Travis and not on us. This one doesn't worry me.

The other one, we can try to use Chrome headless that was just shipped on version 59 (last hope for stable headless testing - haha) or `capybara-webkit` instead of `poltergeist` and see if it's more stable. To contextualize, PhantomJS development was kind of discontinued in favor of Chrome headless (the author started working full-time on Chrome if I'm not wrong). I found a few  resources/examples and I'd like to try Chrome headless. :)

**Comment by vrothberg** [comment]
Awesome, @vitoravelino. Thanks for your input! I am currently looking at potential sources related to dns etc. I'd like to experiment with some Travis settings, e.g. the number of concurrent jobs.

**Comment by vitoravelino** [comment]
Just to document the first error I've mentioned.

```
Capybara::Poltergeist::StatusFailError:
       Request to 'http://127.0.0.1:46477/' failed to reach server, check DNS and/or server status
```

**Comment by ereslibre** [comment]
https://github.com/teampoltergeist/poltergeist/issues/896 might be related.

**Comment by flavio** [comment]
I think that moving to chrome headless would be right choice, I just don't know how much effort it would take right now.

Do you have any idea?

**Comment by vitoravelino** [comment]
We gotta try... from what I searched about it, only a few lines in capybara.rb driver config. Not sure about the side effects. I guess it will need chromedriver but not sure if it downloads automatically and works out of the box.

**Comment by twalpole** [comment]
No, chromedriver is not downloaded automatically so you will have to manually download the latest version of that.  Also, if your tests require multiple windows they can't currently be run with headless chrome due to unsupported functionality/bugs

**Comment by vitoravelino** [comment]
Yeah, you are right. I found this: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/11680/diffs

Need both chrome and chromedriver and selenium-webdriver gem.

**Comment by vitoravelino** [comment]
> Also, if your tests require multiple windows they can't currently be run with headless chrome due to unsupported functionality/bugs

By multiple windows you mean popup windows? I don't think that would be a problem since we don't use that.

**Comment by twalpole** [comment]
Popups, or you have scenarios where you need to have multiple windows open to test. For instance, with chat functionality when you have two users logged in and want to test that when one logs out the status updates in the second users window, etc.

**Comment by ereslibre** [comment]
No longer happening after https://github.com/kubic-project/velum/pull/244, yay!
